--- # Ansible Playbook to deploy or configure static webserver
- hosts: localhost
  connection: local
  remote_user: test
  become: yes
  gather_facts: no
  vars_files:
  - awscreds.yml
  tasks:
  - name: define the security group 
    ec2_group:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      vpc_id: vpc-a1f92dc6
      name: ansible_web_server
      description: this is ec2_group demo
      rules:
       - proto: tcp
         from_port: 80
         to_port: 80
         cidr_ip: 0.0.0.0/0
       - proto: tcp
         from_port: 22
         to_port: 22
         cidr_ip: 0.0.0.0/0
      rules_egress:
       - proto: tcp
         from_port: 80
         to_port: 80
         cidr_ip: 0.0.0.0/0
       - proto: tcp
         from_port: 22
         to_port: 22
         cidr_ip: 0.0.0.0/0
- hosts: aws
  connection: ssh
  remote_user: ec2-user
  become: yes
  become_method: sudo
  gather_facts: yes
  tasks:
  - name: connect to the remote host, execute yum updated
    yum: name=* state=latest
  - name: Install the HTTPD Server
    yum: name=httpd state=latest
  - name: Deply the Static website
    copy: src=index.html dest=/var/www/html/index.html owner=root group=root mode=0655 backup=yes
  - name: Restart the httpd service
    service: name=httpd state=restarted
  - name: Wait for the Http port 80 to be listening
    wait_for: host=ec2-52-10-91-36.us-west-2.compute.amazonaws.com port=80 delay=5
  - name: Install WGET to test the site
    yum:  name=wget state=latest
  - name: test the site
    shell: /usr/bin/wget http://localhost
    register: site_result
  - name: display the site output results
    debug: var=site_result
- hosts: localhost
  connection: local
  remote_user: test
  become: yes
  gather_facts: no
  vars_files:
  - awscreds.yml
  tasks:
  - name: take the snapshot backup of website directory
    ec2_snapshot:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      instance_id: i-063a581ccae0eff1f
      device_name: /dev/xvda
      description: Initial Playbook Static Site Depolyment Backup
      wait: no
    register: snapshot_results
  
